name: Build and Deploy Sphinx Docs to gh-pages

on:
  push:
    branches:
      - feature/add_standard_recon  # or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install sphinx sphinx_rtd_theme

    - name: Build docs
      run: |
        cd docs
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
        publish_branch: gh-pages  # Deploy to the gh-pages branch
        force_orphan: true  # Make sure the gh-pages branch only contains the latest version