name: Build and Deploy Sphinx Docs to gh-pages

on:
  push:
    branches:
      - feature/add_standard_recon  # or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for .GitInfo and .Lastmod

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install sphinx sphinx_rtd_theme

    - name: Build docs
      run: |
        cd docs
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.DOCS_DEPLOYMENT_TOKEN }}  # Use the organization PAT
        publish_dir: ./docs/build/html
        publish_branch: gh-pages
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'